# -*- coding: utf-8 -*-
"""OPIM 244 Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16dhPRf4NfDYB1ubhUtOhbStznICXxnoU

# Main Objectives


*   Tool 1: Stock Price Forecasting & Visualization
* Tool 2: Option Pricing - Black-Scholes Model
  *   Determine BS Inputs from API Data
  * Sensitivity Analysis Graph
  * Delta Hedging Calculator
  * Binomial Tree Generation
* Tool 3: Multi-Asset Portfolio Optimization
"""

# Tool 1
def tool_1():
  from getpass import getpass
  API_KEY = getpass("Please input your AlphaVantage API KEY: ")

  import pandas as pd
  # Import the CSV Data from AlphaVantage
  symbol = input("Please input the ticker symbol for your stock: ")
  symbol = symbol.upper()
  stock_data = pd.read_csv(f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={symbol}&apikey={API_KEY}&datatype=csv')
  df = pd.DataFrame(stock_data)
  print(df)

  import plotly.express as px
  stock_chart = px.line(df,x="timestamp",y="adjusted_close",title=f"{symbol} Stock Price Over Time",labels={"timestamp":"Date","adjusted_close":"Price"})
  stock_chart.show()

# Tool 2
def tool_2():
  import numpy as np
  from scipy.stats import norm
  import matplotlib.pyplot as plt
  import pandas as pd

  option = input("Please enter the ticker symbol for the option: ")
  #expiry_date = input("Please enter the expiry date of your option: ")
  expiry_date = '12-18-2022'
  K = input("Please enter the strike price of your option: ")
  K = int(K)

  from getpass import getpass
  API_KEY = getpass("Please input your AlphaVantage API KEY: ")
  option_data = pd.read_csv(f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={option}&apikey={API_KEY}&datatype=csv')
  df = pd.DataFrame(option_data)
  S = df["adjusted_close"][0]
  df['returns'] = df["adjusted_close"].pct_change()
  sigma = df['returns'].std() * np.sqrt(252)
  print(df)
  r_data = pd.read_csv(f'https://www.alphavantage.co/query?function=TREASURY_YIELD&interval=monthly&maturity=10year&apikey={API_KEY}&datatype=csv')
  df_r = pd.DataFrame(r_data)
  r = df_r["value"][0] / 100
  T = 1


  N = norm.cdf
  print(S,K,T,r,sigma)
  def CallPrice(S, K, T, r, sigma): # Black-Scholes
    d_1 = (np.log(S/K) + (r + sigma**2/2)*T) / (sigma*np.sqrt(T))
    d_2 = d_1 - sigma * np.sqrt(T)
    return S * N(d_1) - K * np.exp(-r*T)*N(d_2)
  def PutPrice(S, K, T, r, sigma):
    d_1 = (np.log(S/K) + (r + sigma**2/2)*T) / (sigma*np.sqrt(T))
    d_2 = d_1 - sigma * np.sqrt(T)
    return K * np.exp(-r * T) * N(-d_2) - S * N(-d_1)
  print("The value of the call is", "{:.2f}".format(CallPrice(S,K,T,r,sigma)))
  print("The value of the put is","{:.2f}".format(PutPrice(S,K,T,r,sigma)))

  greeks_choice = input("View greeks?")
  if greeks_choice == "Y":
    print("GREEKS:")
    OptionDelta = norm.cdf(np.log(S/K) + (r + sigma**2/2)*T / (sigma*np.sqrt(T)))
    OptionGamma = norm.pdf(np.log(S/K) + (r + sigma**2/2)*T / (sigma*np.sqrt(T))) / (S * sigma * np.sqrt(T))
    OptionVega = norm.pdf(np.log(S/K) + (r + sigma**2/2)*T / (sigma*np.sqrt(T))) * S * np.sqrt(T)
    OptionTheta = (-S * norm.pdf(np.log(S/K) + (r + sigma**2/2)*T / (sigma*np.sqrt(T))) * sigma)/(2*np.sqrt(T)) - (r * K * np.exp(-r*T)*norm.cdf(np.log(S/K) + (r + sigma**2/2)*T / (sigma*np.sqrt(T))-(sigma*np.sqrt(T))))
    OptionRho = K * T * np.exp(-r*T)*norm.cdf(np.log(S/K) + (r + sigma**2/2)*T / (sigma*np.sqrt(T))-(sigma*np.sqrt(T)))
    print("Delta = ","{:.3f}".format(OptionDelta))
    print("Gamma = ","{:.3f}".format(OptionGamma))
    print("Vega = ","{:.3f}".format(OptionVega))
    print("Theta = ","{:.3f}".format(OptionTheta))
    print("Rho = ","{:.3f}".format(OptionRho))

  sensitivity_choice = input("View call-put parity graph?")
  if sensitivity_choice == "Y":
    S_min = input("Please input minimum asset price value: ")
    S_min = int(S_min)
    S_max = input("Please input maximum asset price value: ")
    S_max = int(S_max)
    S_range = np.arange(S_min,S_max,0.1)
    calls = [CallPrice(S,K,T,r,sigma) for S in S_range]
    puts = [PutPrice(S,K,T,r,sigma) for S in S_range]
    plt.plot(S_range,calls,label="Call Value")
    plt.plot(S_range,puts,label="Put Value")
    plt.xlabel("$S_0$")
    plt.ylabel("Value")
    plt.legend()

# Tool 3
def tool_3():
  from getpass import getpass
  API_KEY = getpass("Please input your AlphaVantage API KEY: ")

  import pandas as pd
  import numpy as np
  import matplotlib.pyplot as plt
  # Import the CSV Data from AlphaVantage
  symbol_list = []
  stock_list =[]
  df_list = []
  df_p_list = []
  df_p = pd.DataFrame()
  returns_p = pd.DataFrame()

  while True:
    symbol_input = input("Please input the ticker symbol for your stock: ")
    if symbol_input == "DONE":
      break
    else:
      symbol_input = symbol_input.upper()
      symbol_list.append(symbol_input)
  for x in range(len(symbol_list)):
    stock_data = pd.read_csv(f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={symbol_list[x]}&apikey={API_KEY}&datatype=csv')
    stock_list.append(stock_data)
    df_data = pd.DataFrame(stock_data)
    df_list.append(df_data)
    df_p[symbol_list[x]] = df_data['adjusted_close']
    df_p_list.append(df_p)
    returns_p[symbol_list[x]] = df_p[symbol_list[x]].pct_change()

  print("STOCKS:",symbol_list,)
  print(returns_p)

  cov_matrix = returns_p.cov()*252
  cov_matrix

  p_returns = []
  p_volatility = []
  p_weights = []
  assets = len(df_p.columns)
  portfolios = 10000
  i_returns =  returns_p.mean()

  for x in range(portfolios):
    weights = np.random.random(assets)
    weights = weights / np.sum(weights)
    p_weights.append(weights)
    returns = np.dot(weights, i_returns)
    p_returns.append(returns)
    var = cov_matrix.mul(weights, axis=0).mul(weights,axis=1).sum().sum()
    sd = np.sqrt(var)
    ann_sd = sd*np.sqrt(250)
    p_volatility.append(ann_sd)
  
  data = {'Returns':p_returns, 'Volatility':p_volatility}
  for a, b in enumerate(df_p.columns.tolist()):
    data[b+' weight'] = [w[a] for w in p_weights]
  final_df = pd.DataFrame(data)
  print(final_df.head())
  print(cov_matrix)

  final_df.plot.scatter(x='Volatility',y='Returns')
  plt.xlabel("Risk")
  plt.ylabel("Expected Returns")

  min_vol = final_df.iloc[final_df['Volatility'].idxmin()]
  print("Minimum Volatility Portfolio:")
  print(min_vol)

  rf = input("Please input risk tolerance")
  rf = float(rf)
  optimal_p = final_df.iloc[((final_df['Returns']-rf)/final_df['Volatility']).idxmax()]
  print("Optimal Risky Portfolio:")
  print(optimal_p)

# Decision Support System:
print("Hello!")
print("1 - Stock Price Data Visualization & Forecasting")
print("2 - Option Pricing/Delta Hedging Tool")
print("3 - Portfolio Optimization")
tool_number = input("Please select which tool you would like to use (1-3): ")
if tool_number == "1":
  tool_1()
elif tool_number == "2":
  tool_2()
elif tool_number == "3":
  tool_3()
else:
  print("Invalid tool number")